

services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - path: ./templates
          action: sync
          target: /app/templates
        - path: ./requirements.txt
          action: rebuild

  nginx:
    build:
      context: ./docker/nginx_dev
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  db_data: