apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: skill-tracker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: skill-tracker
  template:
    metadata:
      labels:
        app: skill-tracker
    spec:
      containers:
      - name: app
        image: simon6620/skill-tracker:1.1.0  
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-user
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-db
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-password
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret-key
        - name: DB_PORT
          value: "5432"
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: skill-tracker
spec:
  selector:
    app: skill-tracker
  ports:
  - port: 5001
    targetPort: 5001