apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: skill-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skill-tracker
  template:
    metadata:
      labels:
        app: skill-tracker
    spec:
      containers:
      - name: app
        image: simon6620/skill-tracker:1.1.0  
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT  
          value: "5432"
        - name: DB_NAME
          value: "skill_tracker"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-password
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret-key
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: skill-tracker
spec:
  selector:
    app: skill-tracker
  ports:
  - port: 5001
    targetPort: 5001